version: "3.6"

services:
  bpl:
    image: bpl
    container_name: bpl
    restart: unless-stopped
    networks:
      - main-network
    volumes:
      - data:/app/data
    environment:
      - ADMIN_PWD=a
      - RUN_DIST=true

volumes:
  data:

networks:
  main-network:
    name: main-network
    external: true
